import React from 'react';
import { Typography, Card, Row, Col, Tag, Statistic, Button, List } from 'antd';
import { ArrowUpOutlined, FilterOutlined, SearchOutlined, ReloadOutlined } from '@ant-design/icons';

const { Title, Text } = Typography;

export default function History() {
  const stats = [
    { title: 'Total Analyses', value: 1284, prefix: <span className="text-[#065f46] text-sm font-bold block flex items-center gap-1"><ArrowUpOutlined />12%</span> },
    { title: 'Safety Rate', value: '99.2%', prefix: <span className="text-[#cca730] text-sm font-bold block">Stable</span> },
    { title: 'Avg Response', value: '1.4s', prefix: <span className="text-zinc-500 text-sm block">Real-time</span> },
  ];

  const historyData = [
    { id: 1, name: 'Warfarin + Ibuprofen', severity: 'Severe Risk', color: 'error', date: 'Oct 24, 2023', patient: 'ID-9921', borderColor: '#ba1a1a' },
    { id: 2, name: 'Lisinopril + Spironolactone', severity: 'Moderate', color: 'warning', date: 'Oct 22, 2023', patient: 'ID-4402', borderColor: '#cca730' },
    { id: 3, name: 'Amoxicillin + Cetirizine', severity: 'Safe', color: 'success', date: 'Oct 21, 2023', patient: 'ID-1029', borderColor: '#10b981' },
    { id: 4, name: 'Simvastatin + Grapefruit Juice', severity: 'Moderate', color: 'warning', date: 'Oct 19, 2023', patient: 'ID-3381', borderColor: '#cca730' },
  ];

  return (
    <div className="flex-1 bg-surface-light dark:bg-surface-dark transition-colors duration-300 overflow-y-auto h-full">
      <div className="px-8 md:px-20 py-12 max-w-7xl w-full mx-auto space-y-12">
        <div className="space-y-4">
          <Title level={1} className="text-text-light dark:text-text-dark m-0 text-5xl font-extrabold tracking-tight">Analysis History</Title>
          <Text className="text-text-secondary text-lg block max-w-2xl">Review past clinical drug-interaction assessments and safety audits generated by the v3 engine.</Text>
        </div>

        <Row gutter={[24, 24]}>
          {stats.map((s, i) => (
            <Col xs={24} md={8} key={i}>
              <Card className="rounded-xl shadow-soft border-border-light dark:border-border-dark bg-chat-light dark:bg-chat-dark h-40 flex flex-col justify-between">
                <Statistic 
                  title={<span className="uppercase tracking-wider text-xs font-bold text-text-secondary">{s.title}</span>} 
                  value={s.value} 
                  valueStyle={{ fontSize: '2.5rem', fontWeight: 800, color: 'inherit', fontFamily: 'Inter' }}
                  className="text-text-light dark:text-text-dark"
                />
                <div className="mt-4">{s.prefix}</div>
              </Card>
            </Col>
          ))}
        </Row>

        <div className="space-y-6 pb-24">
          <div className="flex justify-between items-center px-1">
            <Title level={3} style={{ margin: 0 }} className="font-bold text-text-light dark:text-text-dark">Previous Interactions</Title>
            <div className="flex gap-2">
              <Button shape="circle" type="text" size="large" icon={<FilterOutlined className="text-text-secondary" />} />
              <Button shape="circle" type="text" size="large" icon={<SearchOutlined className="text-text-secondary" />} />
            </div>
          </div>

          <List
            grid={{ gutter: 16, column: 1 }}
            dataSource={historyData}
            renderItem={item => (
              <List.Item>
                <Card className="w-full rounded-xl hover:shadow-soft transition-shadow border-border-light dark:border-border-dark bg-chat-light dark:bg-chat-dark border-l-4 overflow-hidden" style={{ borderLeftColor: item.borderColor }}>
                  <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-6">
                    <div className="space-y-2">
                      <div className="flex items-center gap-3">
                        <Title level={4} style={{ margin: 0 }} className="text-text-light dark:text-text-dark">{item.name}</Title>
                        <Tag color={item.color} className="uppercase font-bold tracking-tighter rounded-full px-3 py-1 border-none shadow-sm">
                          {item.severity}
                        </Tag>
                      </div>
                      <div className="flex items-center gap-4 text-sm text-text-secondary">
                        <span className="flex items-center gap-1"><span className="material-symbols-outlined text-sm">calendar_today</span>{item.date}</span>
                        <span className="flex items-center gap-1"><span className="material-symbols-outlined text-sm">patient_list</span>Patient: {item.patient}</span>
                      </div>
                    </div>
                    <div className="flex gap-4">
                      <Button type="default" shape="round" size="large" className="font-bold border-border-light dark:border-border-dark text-text-light dark:text-text-dark bg-transparent">View Details</Button>
                      <Button type="primary" shape="round" size="large" icon={<ReloadOutlined />} className="font-bold bg-primary-600 hover:bg-primary-700 text-white border-none">
                        Reload Analysis
                      </Button>
                    </div>
                  </div>
                </Card>
              </List.Item>
            )}
          />
        </div>
      </div>
    </div>
  );
}
